#!/bin/bash
#
# CKDeps 6.2.3 - Dependencies Analysis for Binaries and Packages Installed on Slackware
#
# Created at 2021/04/04 - Mauricio Ferrari - mxnt <m10ferrari1200@gmail.com>
#
# Last Update: 2026/09/06

r='\e[31m'
g='\e[32m'
y='\e[33m'
b='\e[34m'
c='\e[36m'
t='\e[m'

clib='FALSE'
spkg='FALSE'
apkg='FALSE'
cpkg='FALSE'

function info_view
{
printf "\n${b}CKDeps $(grep -Eo "([0-9]+[.])+[0-9]+" <(head -3 $0))
Search installed Slackware packages and check binary dependencies.\n
${g}Syntax: $y${0##*/} $r<options> \e[33margs\n
${g}Options:
    $r-b <binary> $b:$y Search binary dependencies.
    $r-s <pkgs>   $b:$y Basic package search.
    $r-S <pkgs>   $b:$y Advanced package search.
    $r-c <files>  $b:$y Search files in installed packages.\n
${g}Extra Option:
    ${r}i $b:$y Ignore Case Sensitive. <Usage With ${r}s$y,${r}S$y and$r c$y>\n
${g}Example:
    $y${0##*/} $r-b$c /usr/bin/megasync
    $y${0##*/} $r-s$c gcc libtorrent
    $y${0##*/} $r-Si$c qmplay2 wxgtk3
    $y${0##*/} $r-c$c libass libXv\n\n$t"
exit 0
}


# Entrada de Parâmetros

[ -t 0 ] && {
    [ ! "$1" ] && info_view || true
} || {
    set - $* $(cat -) # Suporte a Redirecionamento
}

arg=${*#$1}
[ -z "$arg" ] && info_view

while getopts bsSci option 2>&-; do
    case $option in
        'b') [ "$s" != "TRUE" ] && { clib=TRUE; s=TRUE; } || info_view ;;
        's') [ "$s" != "TRUE" ] && { spkg=TRUE; s=TRUE; } || info_view ;;
        'S') [ "$s" != "TRUE" ] && { apkg=TRUE; s=TRUE; } || info_view ;;
        'c') [ "$s" != "TRUE" ] && { cpkg=TRUE; s=TRUE; } || info_view ;;
        'i') parm='-i' ;;
        *) info_view ;;
    esac
done


#  Verificar Dependências Faltantes

[ "$clib" == "TRUE" ] && {
    [ ! $(($#-1)) -eq 1 ] && {
        printf "\n${r}Too Many Parameters!$t\n\n" >&2
        exit 1
    }

    [ ! -e $arg ] && {
        printf "\n${r}File Does Not Exist!$t\n\n" >&2
        exit 1
    }

    ckbin=$(ldd $arg 2>&-)

    [ -z "$ckbin" ] && {
        printf "\n${r}Not a Valid Binary Executable!$t\n\n" >&2
        exit 1
    }

    cklib=$(awk -F= '{print $1}' <(grep '=> not found' <<< $ckbin))
    printf "\n${y}Missing Dependencies: $b($(wc -w <<< $cklib))$r\n$cklib$t\n\n"
    exit 0
}


#  Operações para Pesquisas

cd /var/lib/pkgtools/packages/
lst=$(printf "%s\n" *)


#  Pesquisa de Pacotes

[ "$spkg" == "TRUE" ] && {
    for pkg in $arg
    {
        found=$(echo -e "$found\n$(grep $parm "$pkg" <<< $lst)")
    }
    found=$(sort -u <<< $found)
    printf "\n${y}Packages Found: $b($(wc -w <<< $found))$c$(sed "s/^/	/" <<< $found)$t\n\n"
    exit 0
}


#  Pesquisa Avançada de Pacotes

[ "$apkg" == "TRUE" ] && {
    for pkg in $arg
    {
        verify=$(grep $parm "^$pkg-[0-9]" <<< $lst)
        [ ! "$verify" ] && notfound=$(echo -e "$notfound\n\t$pkg") || found=$(echo -e "$found\n\t$verify")
    }
    printf "\n${y}Packages Found: $b($(wc -w <<< $found))$g$(sort <<< $found)$t\n"
    printf "\n${y}Packages Not Found: $b($(wc -w <<< $notfound))$r$(sort <<< $notfound)$t\n\n"
    exit 0
}


#  Pesquisa no Conteúdo do Pacote

[ "$cpkg" == "TRUE" ] && {
    for pkg in $(sort <(fmt -1 <<< $arg))
    {
        cntpkg=$(grep $parm "$pkg" <(grep -vE ':|/doc/|install/|/$' $lst))
        cntpkg=$(sed "s|:\([[:alnum:]]*[[:punct:]]*\)*||g" <<< $cntpkg)
        nmpkg=$(sed "s/^/\t/g" <(sort -u <<< $cntpkg))
        found=$(echo -e "$found\n\n$y$pkg: $b($(wc -w <<< $nmpkg)) \n$c$nmpkg$t")
    }
    printf "$(sed "1d" <<< $found)\n\n"
    exit 0
}; info_view
